### ISSUE TITLE
Fails to load SVGs with the same filenames in the same folder

### ISSUE THREAD

**Issue by jakob-fuchs** [jakearchibald/svgomg#100]
I noticed this while downloading and testing different SVG icons. Here are the steps to reproduce:

1. Upload file test.svg located at /home/Downloads to svgomg
2. Delete or move test.svg
3. Put a different file named test.svg into /home/Downloads
4. Upload new test.svg file

The file won't be loaded into the app. I assume that is a problem with the app, but could of course also be 
 an OS or browser problem.

**Comment by XhmikosR** [comment]
I cannot reproduce this here.

**Comment by jakob-fuchs** [comment]
I'll close this 4 year old issue
