### ISSUE TITLE
No option to reset to default optimisation settings in UI

### ISSUE THREAD

**Issue by jonbeddoes-avast** [jakearchibald/svgomg#101]
I don't know why this is the case specifically, but I always encounter problems using this tool when experimenting with the optimisation settings. Regardless of the state of my cookies or whether I am in Incognito mode, I can't seem to just "reset" this tool to the default optimisation toggle values and it always remembers the settings I had last time, even when I don't want this.

**Comment by davidklebanoff** [comment]
Yes, a simple "Restore default settings" button somewhere would be nice.

**Comment by ericcornelissen** [comment]
Seems this issue can be closed @jakearchibald, agreed @jonbeddoes-avast

**Comment by jonbeddoes-avast** [comment]
@ericcornelissen I will have a look and see shortly 👍
