### ISSUE TITLE
Don't round / rewrite transforms

### ISSUE THREAD

**Issue by photopea** [jakearchibald/svgomg#103]
I opened this with default settings and graphics are ruined: https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/gallardo.svg

Rounding transforms is a crazy idea. E.g. when a matrix has all values smaller than 0.001, rounding it to 3 - 4 places will ruin the whole transform.

This option should be either smarter (e.g. take the determinant into account), or removed completely.

**Comment by felixbuenemann** [comment]
Yeah, it will also screw up https://upload.wikimedia.org/wikipedia/commons/a/af/Car_Yellow.svg pretty badly, probably best to leave is disabled by default.

**Comment by alexjlockwood** [comment]
I think you should probably report a bug to svgo instead?

**Comment by XhmikosR** [comment]
@jakearchibald this one can be closed too since it's unrelated to SVGOMG

**Comment by XhmikosR** [comment]
I'm going to close this since it's the same as the issue I reported upstream on https://github.com/svg/svgo/issues/1578
