### ISSUE TITLE
Any plans to enable React-ification of SVG?

### ISSUE THREAD

**Issue by mraak** [jakearchibald/svgomg#104]
Would be a nice feature if it could convert `stop-color `to `stopColor `and similar React needed transforms. Covert styles into objects, etc.

**Comment by jakearchibald** [comment]
I would much rather React supported attributes properly like other vdom-based frameworks.

**Comment by elrumordelaluz** [comment]
In case could be useful there's [svgr](https://github.com/smooth-code/svgr) to _Tranform SVG into React components_

Also, [now _React_ pass `attrs`](https://reactjs.org/blog/2017/09/26/react-v16.0.html#support-for-custom-dom-attributes) without problem

**Comment by TrySound** [comment]
Check also `@svgo/jsx` package
https://github.com/svg/svgo-components/tree/main/packages/svgo-jsx
