### ISSUE TITLE
Heads-up: transformsWithOnePath plugin was recently removed

### ISSUE THREAD

**Issue by alexjlockwood** [jakearchibald/svgomg#107]
In a recent version of svgo it looks like the `transformsWithOnePath` plugin has been removed. Thought I would give you a heads up since the svgo changelog doesn't mention this (I've asked the maintainer if he can update the changelog with details though).

Link to the svgo commit: https://github.com/svg/svgo/commit/055e303607d53a3d539761d8727d86c03b2e88c1#diff-63dc9087c660611bdf3fcb1a1257247a

**Comment by jakearchibald** [comment]
I tend to use https://github.com/svg/svgo/blob/master/.svgo.yml when updating the list of plugins.

**Comment by alexjlockwood** [comment]
It looks like a few of the existing plugins have been enabled by default too, beginning in v1.0.2.
