### ISSUE TITLE
SVG markup only works if appending empty <g/> element to end

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [jakearchibald/svgomg#110]
Hello,

I can paste this markup:

    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 277.58 277.58"><path fill="#010002" d="M138.46 164.287c-38.628 0-69.925-37.52-69.925-83.767C68.535 34.277 99.832 0 138.46 0z"/><g/></svg>

But not this:

    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 277.58 277.58"><path fill="#010002" d="M138.46 164.287c-38.628 0-69.925-37.52-69.925-83.767C68.535 34.277 99.832 0 138.46 0z"/></svg>

Then I get an error saying "Minifying error: Cannot read property 'value' of undefined"

**Comment by alexjlockwood** [comment]
Are you still able to reproduce this? Because I am not.

**Comment by bjorn-ali-goransson** [comment]
Hi

This happens when some kind of application state is ruined. Have met
similar (but different) errors and could recreate them repeatedly and was
going to report them but then noticed they were gone upon closing the page
and reopening.

Björn

Den 4 dec 2017 08:47 skrev "Alex Lockwood" <notifications@github.com>:
