### ISSUE TITLE
Generate CSS background code (feature request)

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [jakearchibald/svgomg#111]
It'd be nice to have something like this as a separate tab on the tool (next to "CODE"):

https://bjorn-ali-goransson.github.io/convert-svg-to-css-background.html

On the left hand column, you can paste SVG markup. On the right hand column, you will get a complete `background-image:` CSS snippet, encoding only the minimally required characters to work in IE etc. (that information is from https://css-tricks.com/probably-dont-base64-svg/ )

Also, you can paste such CSS snippets into the right hand column to get your SVG markup back!

**Comment by bjorn-ali-goransson** [comment]
Also, note that IE wants explicit width and height attributes along with its viewbox in order to scale properly (without `background-size`).

**Comment by Haroenv** [comment]
solvable by #125 I think

**Comment by bjorn-ali-goransson** [comment]
Nice!
