### ISSUE TITLE
Add new plugins

### ISSUE THREAD

**Issue by strarsis** [jakearchibald/svgomg#116]
I just noticed that the svgomg (web) GUI misses some new plugins ([inlineStyles](https://github.com/svg/svgo/pull/592) and [prefixIds](https://github.com/svg/svgo/pull/700)).

**Comment by jakearchibald** [comment]
Working on it. See the pull requests and next-version branch.

**Comment by alexjlockwood** [comment]
inlineStyles just got published! :)
