### ISSUE TITLE
Option to Remove Self-closing Tags

### ISSUE THREAD

**Issue by pcarper** [jakearchibald/svgomg#118]
An option to remove self-closing tags would be a nice enhancement to support legacy HTML 4/5 requirements. 

Example Before: `<path d="M0 0h24v24H0z" fill="none"/>`
Example After: `<path d="M0 0h24v24H0z" fill="none"></path>`

Currently, I'm using this regex `<\s*([^\s>]+)([^>]*)/\s*>` to match self-closing tags and replacing matching groups with `<$1$2></$1>`.

btw, SVGOMG is a game changer. Great work!

**Comment by jakearchibald** [comment]
Glad the tool helps! Closing this in favour of https://github.com/svg/svgo/issues/870, as that's where the transforms are.
