### ISSUE TITLE
SVGOMG does not remember my settings

### ISSUE THREAD

**Issue by ConnorsFan** [jakearchibald/svgomg#121]
A few weeks or months ago, SVGOMG remembered the settings from one session to the next. That is not the case anymore. For example, if I uncheck "Remove viewBox" and I check "Prefer viewBox to width/height", I get the correct result during the current session. If I close the browser, restart it and go to SVGOMG and open an SVG file, the settings are back to their default values.

Tested in Chrome and Firefox on Windows 7.

**Comment by jakearchibald** [comment]
Huh, yes, I do seem to have broken that. Will fix.

**Comment by jakearchibald** [comment]
This is fixed & deployed now. Sorry to those who were missing this feature!

Don't be like me, write tests!
