### ISSUE TITLE
Is it possible to embed in my own application?

### ISSUE THREAD

**Issue by candidodmv** [jakearchibald/svgomg#122]
Hello, before of all, congratulations for this amazing UI implementation. But my question is, there some way to embed the SVGO or even svgomg in my own application? to optimize the svg files uploaded to my web application? In case some solution based pure client side with Javascript or build on  Microsoft .NET platform?

Thank you!

**Comment by lucasa** [comment]
I want to embed in a webapp too!

**Comment by candidodmv** [comment]
Hi @lucasa, I did found a alternative, in case using the engine that runs behind svgomg :  [SVGO](https://github.com/svg/svgo) with this library you can choose the best implemantation that match with the technology that you are using. In my case, as we are based on Microsoft .NET the road that we follow is use [Edge.js](https://github.com/tjanczuk/edge) one solution that makes possible Node.js and .NET talk together. Good luck and hope this can be useful to you.
