### ISSUE TITLE
update svgo to 1.0.4

### ISSUE THREAD

**Issue by staabm** [jakearchibald/svgomg#130]
please update the bundled svgo

https://github.com/svg/svgo/releases/tag/v1.0.4

**Comment by SignpostMarv** [comment]
Please update to 1.0.5 re: svg/svgo#963

**Comment by staabm** [comment]
1.1.0 was released https://github.com/svg/svgo/commit/e7bdce66ed1f47bed291ddda2ce9871eb78bd327

**Comment by RoyTinker** [comment]
Aaaaaand, `svgo` is now at 1.1.1.

@jakearchibald would you accept a PR for this?

**Comment by jakearchibald** [comment]
Absolutely

**Comment by ChildishGiant** [comment]
1.3.0 is now out and 1.0.3 is still on master here. Would a straight upgrade of the package.json version number be enough or would more feature toggles be needed?

**Comment by jakearchibald** [comment]
It's more than an update to package.json. you need to check the plugins are in sync.
