### ISSUE TITLE
Bulk-edit does not work because of selection problems

### ISSUE THREAD

**Issue by rugk** [jakearchibald/svgomg#131]
https://github.com/jakearchibald/svgomg/issues/64 does not work, because I have no idea how to input multiple files. 

Drag and drop only seems to add one file, and in the "Open file" dialog I also can only select one file to upload.

Firefox 58
Linux x64/GNOME

/cc @sompylasar

**Comment by sompylasar** [comment]
@rugk Hi, thanks for the report. Are you using my fork with #64 ? Please provide the URL if it's not locally hosted. This hasn't been released to the main https://jakearchibald.github.io/svgomg/

**Comment by rugk** [comment]
Ah, so that's the reason. So this has been merged around half a year ago, but not yet released on the main site? Huh… strange.

**Comment by sompylasar** [comment]
Closed, not merged. The changes were rejected with a note that anyone can spin up my fork locally to use them until a maintainer-approved implementation appears.

**Comment by sompylasar** [comment]
Here's the rejection reason from the maintainer: https://github.com/jakearchibald/svgomg/pull/98#issuecomment-352699767

**Comment by rugk** [comment]
Can't you also host you fork at GitHub Pages? If I were to user this locally, I could user svgo itself.
The web version is just much easier to use.

**Comment by jakearchibald** [comment]
Yeah, https://github.com/jakearchibald/svgomg/pull/98#issuecomment-352699767 is the summary.

Providing a way to get the SVGO command line to run the selected optimisation across one or more files sounds more useful.

**Comment by sompylasar** [comment]
@rugk Thank you for the interest. Maybe someday I'll get to that. In the meantime, you can clone my fork and keep it launched locally.
