### ISSUE TITLE
Activating Multipass option breaks the app

### ISSUE THREAD

**Issue by villelahdenvuo** [jakearchibald/svgomg#137]
Steps to reproduce:
1. Open https://jakearchibald.github.io/svgomg/
2. Open Demo svg
3. Enable Multipass
4. Observe `svgo.js:36 Uncaught (in promise) Error: abort at _currentJob.abortCurrent.then (svgo.js:36)`

Any subsequent config change results in the same error, even if you try disabling the Multipass option.

Environment:
Google Chrome | 67.0.3396.79 (Official Build) (64-bit)
OS | Mac OS X
JavaScript | V8 6.7.288.44

**Comment by jakearchibald** [comment]
I've removed the multipass option until I have time to figure out what's going on here.

**Comment by TrySound** [comment]
Looks like it works now
