### ISSUE TITLE
Wrong arc optimization

### ISSUE THREAD

**Issue by shrpne** [jakearchibald/svgomg#139]
Today I used https://jakearchibald.github.io/svgomg/ tool and found a bug in path optimization.
I got wrong large-arc-flag in the arc `a4.98 4.98 0 1 0-3.38 8.66`, it should be `a4.98 4.98 0 0 0-3.38 8.66`

Initial path
d="M20,9 C26.085938,9 31,13.914062 31,20 C31,22.679688 30.046876,25.125 28.46875,27.03125 C27.609376,24.59375 25.75,22.632812 23.375,21.664062 C24.367188,20.75 25,19.445312 25,18 C25,15.25 22.75,13 20,13 C17.25,13 15,15.25 15,18 C15,19.445312 15.632812,20.75 16.625,21.664062 C14.25,22.632812 12.398438,24.59375 11.539062,27.03125 C9.953126,25.125 9,22.679688 9,20  C9,13.914062 13.914062,9 20,9 Z " 

Optimization output
d="M20 9a10.99 10.99 0 0 1 8.47 18.03 9.04 9.04 0 0 0-5.1-5.37A4.98 4.98 0 0 0 20 13a4.98 4.98 0 **1** 0-3.38 8.66 9.03 9.03 0 0 0-5.08 5.37A10.99 10.99 0 0 1 20 9z"

Expected output
d="M20 9a10.99 10.99 0 0 1 8.47 18.03 9.04 9.04 0 0 0-5.1-5.37A4.98 4.98 0 0 0 20 13a4.98 4.98 0 **0** 0-3.38 8.66 9.03 9.03 0 0 0-5.08 5.37A10.99 10.99 0 0 1 20 9z"

**Comment by jakearchibald** [comment]
Please test this with the latest SVGO and file a bug there if it's an issue.
