### ISSUE TITLE
White SVGs are hard to see against background

### ISSUE THREAD

**Issue by pranksinatra** [jakearchibald/svgomg#143]
When compressing small, white icons at work, I find myself consistently jumping into DevTools and changing the page's background to a darker color, so I can see the icon's edges.

#f2f2f2 (current background-color)
![image](https://user-images.githubusercontent.com/9473554/44870690-bb4e6c80-ac45-11e8-8ab1-3d7bab3385e6.png)

#333
![image](https://user-images.githubusercontent.com/9473554/44870709-c7d2c500-ac45-11e8-9b42-4579eb337325.png)

We could detect SVG colors on the fly and switch to dark mode if they're lighter on average than a certain threshold. 

Alternatively, a little UI toggle between light & dark mode would do the job (though there's already so many toggles I'd hate to add to them).

I'd be happy to submit a PR if either of these options look promising. Thanks again for such a handy tool!

**Comment by pranksinatra** [comment]
Wow, I just realized that the paint bucket button does exactly this. Haha, must have been a long day at work. I'll close this out.

**Comment by jakearchibald** [comment]
I guess the icon isn't intuitive. Maybe the one I used on http://www.spritecow.com is better?

**Comment by badcat** [comment]
@jakearchibald YES!  I like the grid icon MUCH better than the bucket. TBH, I'd completely overlooked that icon till @pranksinatra mentioned this.
