### ISSUE TITLE
Bad file extension

### ISSUE THREAD

**Issue by xavierfoucrier** [jakearchibald/svgomg#144]
I accidentally found this little issue: when using a file named `test.sgv` (write by mistake) as input, **the GUI keeps the original file extension** and output `.sgv`. Keeping the filename is a good idea, but the extension must end with `.svg`.

I know that users have to pay attention to filenames, but a file that is output by a data conversion process should fit the data format target, and so respect the SVG file extension.

Nice and useful web application btw :wink:

**Comment by XhmikosR** [comment]
@jakearchibald I'm not sure about this. I mean, I see the above point and it probably makes sense if an image that was loaded, was successfully compressed.

**Comment by xavierfoucrier** [comment]
Closing the issue due to **inactivity**.
> Feel free to reopen again when needed.
