### ISSUE TITLE
Enable pasting SVG without clicking the "Paste markup" button

### ISSUE THREAD

**Issue by fvsch** [jakearchibald/svgomg#149]
In Figma, if you have SVG code in your clipboard and just hit Ctrl+V (or Cmd+V on macOS) in a document, it creates a new frame with your SVG in that document. It's a really nice way to work with SVG quickly.

It would be great to have the same in SVGOMG. It probably needs no UI. Only need to listen for the right keyboard shortcut on the page. Though I guess there might be security restrictions that Figma works around with an invisible input, I’m not sure.

**Comment by gismya** [comment]
I got annoyed when copying icons from Figma via SVGOMG. So instead of spending a few minutes extra doing that, I spent.. way more time making the necessary code changes. PR here: https://github.com/jakearchibald/svgomg/pull/261
