### ISSUE TITLE
Gulp version syntax in package.json causes installation issues

### ISSUE THREAD

**Issue by macandcheese** [jakearchibald/svgomg#152]
In`package.json`, the line `"gulp": "github:gulpjs/gulp#4.0"` results in installation errors:

```
npm ERR! Command failed: git checkout 4.0
npm ERR! error: pathspec '4.0' did not match any file(s) known to git.
```
This seems related to https://github.com/gulpjs/gulp/issues/2078 and other issues referenced there.

Changing that line to `"gulp": "^4.0.0"` solves the issue.

**Comment by tony-topper** [comment]
Thanks @macandcheese.  I had the same problem and your solution fixed it for me as well.   Have you made a pull request?

**Comment by TrySound** [comment]
Already fixed
