### ISSUE TITLE
 chrome browser its not loading.

### ISSUE THREAD

**Issue by sam-ani** [jakearchibald/svgomg#156]
HI I build the SVGOMG source code and i got build folder created and i ran command >npm run serve
below output came. But in chrome browser its not loading.

http://127.0.0.1:8080
Am getting 
This page isn’t working 127.0.0.1 sent an invalid response.
ERR_INVALID_REDIRECT

gulp watch & http-server build -c-1

[13:41:34] Using gulpfile ~\Desktop\svgomg-master\gulpfile.js
[13:41:34] Starting 'watch'...
[13:41:34] Starting 'clean'...
[13:41:35] 'clean' errored after 651 ms
[13:41:35] Error: EBUSY: resource busy or locked, rmdir 'C:\Users\praja\Desktop\svgomg-master\build'
[13:41:35] 'watch' errored after 666 ms
Starting up http-server, serving build
Available on:
  
  http://127.0.0.1:8080
Hit CTRL-C to stop the server
[Tue Jun 25 2019 13:41:47 GMT-0400 (Eastern Daylight Time)] "GET /" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
[Tue Jun 25 2019 13:41:51 GMT-0400 (Eastern Daylight Time)] "GET /" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
13:41:35] 'clean' errored after 651 ms[Tue Jun 25 2019 13:44:14 GMT-0400 (Eastern Daylight Time)] "GET /" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
[Tue Jun 25 2019 13:44:14 GMT-0400 (Eastern Daylight Time)] "GET /" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
[Tue Jun 25 2019 13:44:19 GMT-0400 (Eastern Daylight Time)] "GET /" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
[Tue Jun 25 2019 13:44:27 GMT-0400 (Eastern Daylight Time)] "GET /" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
[Tue Jun 25 2019 13:44:37 GMT-0400 (Eastern Daylight Time)] "GET /" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
[Tue Jun 25 2019 13:44:39 GMT-0400 (Eastern Daylight Time)] "GET /" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"

**Comment by sam-ani** [comment]
Service worker event waitUntil() was passed a promise that rejected with 'TypeError: NetworkError when attempting to fetch resource.'. sw.js:1:1050
Source map error: request failed with status 404
Resource URL: http://127.0.0.1:8080//index.html
Source Map URL: head.css.map[Learn More]
Navigated to http://127.0.0.1:8080//index.html
Source map error: request failed with status 404
Resource URL: http://127.0.0.1:8080//index.html
Source Map URL: head.css.map[Learn More]
Service worker event waitUntil() was passed a promise that rejected with 'TypeError: NetworkError when attempting to fetch resource.'. sw.js:1:1050
Navigated to http://127.0.0.1:8080//index.html
Source map error: request failed with status 404
Resource URL: http://127.0.0.1:8080//index.html
Source Map URL: head.css.map[Learn More]
Service worker event waitUntil() was passed a promise that rejected with 'TypeError: NetworkError when attempting to fetch resource.'. sw.js:1:1050

**Comment by XhmikosR** [comment]
Something went wrong locally. Try to unregister the service worker and it should be OK again.
