### ISSUE TITLE
"Remove viewBox" doesn't

### ISSUE THREAD

**Issue by tigt** [jakearchibald/svgomg#16]
Before:

![screenshot 2015-02-12 12 19 36](https://cloud.githubusercontent.com/assets/8072522/6172931/0e1c1c5a-b2b2-11e4-978c-61cc0ef918d1.png)

After:

![screenshot 2015-02-12 12 20 26](https://cloud.githubusercontent.com/assets/8072522/6172932/0e1d04da-b2b2-11e4-8308-d6fa679a1d49.png)

This isn't a big problem, since all things considered one almost always wants a `viewBox`. What's interesting, though, is that it seems to trigger another go-round on the multipass compressor, which shaved off another 3% (at the expense of visual quality).

**Comment by jakearchibald** [comment]
I should update the wording here. It only removes the viewbox if there's an equivalent width/height & the `viewBox` is redundant. But yeah, it's almost always better to remove the width & height instead in this case.

**Comment by kpym** [comment]
+1 to clarify this in the interface.
It will be nice if we hover some option to have some kind of explanation.

**Comment by Tigt** [comment]
Oh, it looks like this was updated; now it says "Prefer viewBox to width/height."

**Comment by kpym** [comment]
@Tigt no, not for me. This screenshot is from today:
![svgomg_remove_viewbox](https://cloud.githubusercontent.com/assets/3142701/10709396/cf7b4aaa-7a2c-11e5-9d06-7762d98f632d.png)

**Comment by tigt** [comment]
![A settings toggle labeled “Prefer viewBox to width/height.”](https://cloud.githubusercontent.com/assets/8072522/23646027/07613cf6-02dd-11e7-9d15-75b118574967.png)

I should have closed this a year ago. My bad!
