### ISSUE TITLE
Files now break / corrupt when uploading to GT Sport.

### ISSUE THREAD

**Issue by HansLoser** [jakearchibald/svgomg#167]
Hi, I use SVGOMG almost daily to shrink SVGs and upload them to the game Gran Turismo Sport via their website.  GT Sport has a 15kb limit per file, so SVGOMG is absolutely vital in the process of getting complex images onto the game.

Since the latest update to SVGOMG I (and a friend also) have found the SVGs now break (distortion / stretching / glitchy looking) when uploading to the game.  I have uploaded un-OMG'd files below 15kb and ones shrunk by SVGminify.com (v.limited in comparison to your tool) and they work fine.

Here is an image to illustrate what happens when the files get onto the game.  The 1st 4 files pictured were put through SVGOMG.  The 5th was below 15kb so didn't go through SVGOMG.
![image](https://user-images.githubusercontent.com/56097686/66090603-186cce00-e57c-11e9-9175-3d32ea29ac61.png)

Each time I back out of where the SVG's are found in-game I find their appearance has glitched in a different way to the last.

Please do what you can to investigate this issue.  SVGOMG is very important to the GT Sport community.  

Also, is there a way to access the previous version in the meantime?  Apologies if this is a silly question, I am not used to GitHub.  Thank you.

**Comment by tigt** [comment]
Can you provide the SVG files before/after?

If you could provide one that was previously SVGOMG'd that used to work and doesn't now, that would be even better.

**Comment by HansLoser** [comment]
> 
> 
> Can you provide the SVG files before/after?
> 
> If you could provide one that was previously SVGOMG'd that used to work and doesn't now, that would be even better.

Yes, here is a [zip](https://github.com/jakearchibald/svgomg/files/3688290/SVGOMG.167.zip) containing the following files: 



- OEP_old_unedited.svg.  Original file made with Adobe Illustrator, untouched by SVGOMG.
- OEP_old_omg.svg.  That original file put through SVGOMG at the time that I made it (May 2018).  This still uploads to the game and works as normal.
- 9 new files corresponding to each precision level currently available from SVGOMG.

Previously I would leave most of the files I put through SVGOMG on the Precision 1 setting.  I found that was able to shrink most files ~70kb down to the <15kb needed for the game whilst still keeping acceptable appearance.   Precision 0 would either reduce the quality too much, or break altogether if my original file included an object with <100% opacity.


As you will see from the image to follow there are now visible issues with all files put through Precision levels 0 to 3.  Precision Level 4 also had issues with previewing in game, but when you apply it to a car in game it works okay.  On the left side are the SVG's applied to a surface in-game and on the right is the layer preview panel in-game.  All files look normal when previewed on the website where you upload them.

![game left layers panel right](https://user-images.githubusercontent.com/56097686/66168457-31858580-e635-11e9-96ae-a3ccff4609ae.jpg)

Thanks for looking into this!  I will see if I can get some more examples.

**Comment by tigt** [comment]
I'll dig into this more later this week. In the meantime, you can spin up
your own SVGOMG reverted to a later version by forking this repository here
on GitHub.

**Comment by jakearchibald** [comment]
@HansLoser can you confirm that one of these is causing issues but the other isn't? https://gist.github.com/jakearchibald/d2f0cb23928509f106ed9c258e056a53

It's weird because I'm not seeing much different between the files.

**Comment by HansLoser** [comment]
@jakearchibald  I uploaded the linked files to the game to check and yeah 'svgomg-latest.svg' is the one with that breaks in game.  Here's a picture to illustrate:
![comparison](https://user-images.githubusercontent.com/56097686/66262519-f4a6c380-e7d9-11e9-9211-e4a0cae826d6.jpg)

@tigt  Thanks I'll take a look into doing that.  

Here's another set of files that used to work and now don't for anyone to take a look at:  [duct.zip](https://github.com/jakearchibald/svgomg/files/3693840/duct.zip)  
Same sort of thing, though due to the smaller size of the original file (I'm guessing) less of them seem to break in-game.  Only precisions 1 and 3 show errors this time.  'duct_old_omg.svg' is from September 22nd and works perfectly.  There is an example image in the zip.  Thanks to you both for looking into this.

**Comment by viljamis** [comment]
I’m seeing a similar issue with the new version when first using svgomg on an SVG and then trying to open it later in the Sketch app. 

A little background: We use SVGOMG on our design system’s CI pipeline to generate assets for both devs and designers which is how we noticed the issue in the first place as suddenly our whole icon library for designers was broken.

This is what happens to all icons in Sketch for us (with older svgomg version this did not happen):

<img width="876" alt="Screen Shot 2019-10-11 at 7 11 37" src="https://user-images.githubusercontent.com/671836/66623971-d20c1480-ebf6-11e9-82d0-055a993f234f.png">

The one on the left side is compressed using ImageOptim lossy compression and the on right is using the newest version of svgomg.

**Comment by jakearchibald** [comment]
Could you file this with SVGO? https://github.com/svg/svgo. It's seems like an issue with the underlying engine. It feels like SVGO is creating SVG that some renderer(s) simply can't handle.

**Comment by viljamis** [comment]
@jakearchibald Will do! Now realized myself as well that at least my comment is in the wrong repo. My bad.

**Comment by viljamis** [comment]
Looks like this might be a solution to our problem at least: https://github.com/svg/svgo/issues/1137#issuecomment-517738958

Will be testing next week.

**Comment by jakearchibald** [comment]
Thanks! I'll look to expose this option in SVGOMG.

**Comment by sashamorozov** [comment]
@viljamis thank you, this worked for me!
However `mergePaths` is one of the most important rules, it helps greatly reduce file size.

**Comment by irsanmulia9** [comment]
Here you can use the optimize (opt) file. I using Inkscape to edit and save. To compress, I use Adobe Illustrator CS5 with decimal compress 2. From 18 kb to 14kb. Check my attachment and try upload it first.
[oep_edited_by_id.zip](https://github.com/jakearchibald/svgomg/files/4141974/oep_edited_by_id.zip)

**Comment by yisibl** [comment]
I have fixed this issue in svgo 2.0.3，this PR https://github.com/svg/svgo/pull/1353 disables the `noSpaceAfterFlags` option by default.

**Comment by XhmikosR** [comment]
@TrySound Can you check this? AFAICT it was an issue with svgo 1.x.

**Comment by TrySound** [comment]
Yes, noSpaceAfterFlags is disabled by default

**Comment by TrySound** [comment]
Images are still corrupted with low precision though it's inevitable when small viewbox is used.
