### ISSUE TITLE
Unable to build: Rollup Error / 'babel-minify' / Invalid typeof value

### ISSUE THREAD

**Issue by admvx** [jakearchibald/svgomg#169]
Thanks for this awesome project!

I tried to build this locally after running `npm install` and ran into this error:
```
Rollup Error Error: Error transforming bundle with 'babel-minify' plugin: unknown: Invalid typeof value
    at error (/Users/adam/git/svgomg/node_modules/rollup/dist/rollup.js:185:14)
    at /Users/adam/git/svgomg/node_modules/rollup/dist/rollup.js:9216:5 {
  code: 'BAD_BUNDLE_TRANSFORMER',
  plugin: 'babel-minify'
}
```

I'm running node v12.11.1 and npm 6.12.0. Bumping `rollup-plugin-babel-minify` to the next major version appears to fix the issue, but I can't think why this new issue would emerge, given that the dependency hasn't changed in two years 🤔 https://github.com/jakearchibald/svgomg/blame/master/package.json#L20

**Comment by TrySound** [comment]
Babel-minify is removed
