### ISSUE TITLE
SVG codes should be indented with U+0009

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [jakearchibald/svgomg#171]
Character tabulation (U+0009) is usually used to indent the source codes, but SVGOMG doesn’t make use of that while _Prettify markup_ is selected. This can be reproduced if you open the website, click Demo, and select Prettify markup.

**Comment by David263** [comment]
Apparently, Jake Archibald does not believe in responding to simple bug reports. Not very professional.

**Comment by jakearchibald** [comment]
I'm not getting into a tabs vs spaces debate here. And secondly, @David263 (the 263rd David), fuck you and your sense of entitlement when it comes to free software.

**Comment by David263** [comment]
jakearchibald, You are the owner of this repository, so being uncivil is even more egregious. I will see if there is any way I can complain to GitHub.

**Comment by David263** [comment]
I have filed my complaint. I advise you to reconsider the way you interact with people. Abuse is unacceptable anywhere on the Web.
