### ISSUE TITLE
SVG not working in Adobe Illustrator

### ISSUE THREAD

**Issue by o-t-w** [jakearchibald/svgomg#172]
I have optimized some SVG icons that look fine when I open them in the browser but when I open them in Adobe Illustrator they don't display on the artboard.

**Comment by paulocoghi** [comment]
Partially related to your issue (but not completely related), when I generate pure SVGs on Illustrator, it's still common for it to generate incorrect SVGs. For example, wrong ways to express the font names.

There is a small, but improbable, possibility that Illustrator is not correctly interpreting the SVG file.

**Comment by paulocoghi** [comment]
If this is not the problem, I believe it's better to open an issue on https://github.com/svg/svgo repository.

On this issue, attach your original SVG, the optimized one and inform which optimizations you have chosen.

**Comment by tigt** [comment]
This smells like it might be related to #167

**Comment by BB-000** [comment]
Same issue, Illustrator just shows a little "x" in the top left corner of the artboard, svg works fine elsewhere

**Comment by gravnetic** [comment]
It is because SVGO is stripping attributes Illustrator relies on to show the SVG.

**Comment by XhmikosR** [comment]
@jakearchibald I'd close this too since it doesn't seem to be related to SVGOMG

**Comment by tomgidden** [comment]
I've _think_ the SVGO param `noSpaceAfterFlags` borks Illustrator.  I thought for a while it was the conversion of curves to arcs that was the problem (see #211), but I think it's more that this feature is more likely to happen with arcs than curves.

The example in https://github.com/svg/svgo/blob/master/plugins/convertPathData.js#L31 is:
```
// a20 60 45 0 1 30 20 → a20 60 45 0130 20
```
and I think it's that `0 1 30` to `0130` conversion that Illustrator doesn't like. I'm not surprised, as it's a pretty extreme compaction.  I can understand `0 0 ` being reduced to `00 `.


I've found that if I manually go through SVGOMG'ed paths and replace ` 00` with ` 0 0` or sometimes ` 0 0 ` (according to context) some of my paths reappear.

If I run the same SVG through `svgo` with default settings, I don't have the problem.

A (somewhat) isolated case:  here, the original shape from Illustrator is blue; the working version from `svgo` is in green; and the broken version from `svgomg` is in red -- blue and green will display in Illustrator, but red won't.

[test5.svg.txt](https://github.com/jakearchibald/svgomg/files/6305543/test5.svg.txt)

**Comment by TrySound** [comment]
SVGO disabled noSpaceAfterFlags by default. Should be fixed now.
