### ISSUE TITLE
Replace kebab-case with camelCase

### ISSUE THREAD

**Issue by lanmonster** [jakearchibald/svgomg#182]
Recently, I was using svgomg to preprocess svgs for react components and found myself manually changing "fill-rule" to "fillRule" for each component.

As a react developer,
I can export svgs with camelCase property names,
so that I can use the results as react components.

**Comment by TrySound** [comment]
Check `@svgo/jsx` package
https://github.com/svg/svgo-components/tree/main/packages/svgo-jsx
