### ISSUE TITLE
[Feature Request] Copy settings as CLI string

### ISSUE THREAD

**Issue by ptim** [jakearchibald/svgomg#184]
I love previewing SVGO settings in SVGOMG, thanks!

It would be fantastic to have a button at near the config settings "Copy settings as CLI", like:

`npx svgo test.svg --precision=n  --config="<ESCAPED_JSON_STRING>"`

**Comment by ericbf** [comment]
I'd like to see this too!

**Comment by XhmikosR** [comment]
@jakearchibald this seems duplicate of #11

**Comment by ptim** [comment]
I missed the previous ticket - I'll close this one and continue to follow over at #11 👍

**Comment by WebMechanic** [comment]
I'd love to see **anything like this**, too!

There are now 3 separate request **since 2015** to implement this feature in one way or another #11, #50 and this one #184.
