### ISSUE TITLE
Shrink viewbox to svg image size

### ISSUE THREAD

**Issue by danielrob** [jakearchibald/svgomg#190]
Hi there! I absolutely love and appreciate this project. Thank you, thank you, thank you. 

One item that I always had to deal with after svgomg'ing my svg's was shrinking the viewbox to remove all whitespace around the svg paths. 

Although I would love this feature in svgomg out of the box I also found https://jsfiddle.net/knLbjc9a/4/ which has a very simple method to maximally shrink the viewbox with just a few lines of javascript. This might be useful to others while it is not/until it is a feature in svgomg :). 

```
var svg = document.getElementsByTagName("svg")[0];
var bbox = svg.getBBox();
var viewBox = [bbox.x, bbox.y, bbox.width, bbox.height].join(" ");
svg.setAttribute("viewBox", viewBox);
prompt("Copy to clipboard: Ctrl+C, Enter", svg.outerHTML);
```

**Comment by jenstroeger** [comment]
@danielrob, looks much like [this gist](https://gist.github.com/john-doherty/2ad94360771902b16f459f590b833d44) (see also the documentation on [`getBBox()`](https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement/getBBox)). However, this doesn’t really _remove_ the padding but only

> allows us to determine the coordinates of the smallest rectangle in which the object fits.

Would be great actually _trim_ that space completely.

**Comment by mshaw42** [comment]
The SVG bounding box needs to be shown with a 'Trim viewBox' option. When activated this updates the visual bounding box accordingly.

There also needs to be an AI robot that detects if the SVG file is a logo, then finds the brand guidelines, parses the brand guidelines and, if some clumsy illiterate oaf has removed the whitespace, adds the correct whitespace according to the style guide. Call it the 'Zealous Pad' option.

**Comment by jakearchibald** [comment]
SVGOMG is a GUI around SVGO. If you want new SVG processing features in SVGOMG, they need to appear in SVGO first.
