### ISSUE TITLE
Update to svgo 2.x

### ISSUE THREAD

**Issue by XhmikosR** [jakearchibald/svgomg#208]
@jakearchibald svgo 2.x has some nice fixes and improvements :)

**Comment by yisibl** [comment]
svgo 2.x has made significant improvements in compression security, please upgrade as soon as possible.

**Comment by yisibl** [comment]
https://github.com/svg/svgo/releases/tag/v2.0.3

**Comment by TrySound** [comment]
Done in https://github.com/jakearchibald/svgomg/pull/224

**Comment by Jexsie** [comment]
I want to, but i don't know how to!??
