### ISSUE TITLE
Is this project a browserfied version of SVGO?

### ISSUE THREAD

**Issue by nikkwong** [jakearchibald/svgomg#21]
Hi, 

I'm curious as to what this build actually is and how it was put together. I did a ```browserify svgo.js -o svg.js``` and the output looks nothing like what you have running at https://jakearchibald.github.io/svgomg/js/page.js

Out of curiosity, what exactly was used to make this project?

Many thanks.

**Comment by jakearchibald** [comment]
page.js is just frontend GUI stuff.

SVGO is indeed browserified, but in a worker https://github.com/jakearchibald/svgomg/blob/master/src/js/svgo-worker/main.js
