### ISSUE TITLE
Missing <?xml - SVG files are XML files

### ISSUE THREAD

**Issue by szepeviktor** [jakearchibald/svgomg#217]
Please consider **adding** `<?xml version="1.0" encoding="UTF-8" standalone="no"?>` to downloaded files.
The standard says: https://www.w3.org/TR/SVG11/struct.html#NewDocument

SVG-s copied to the clipboard could remain the way they are as people tend to paste them into HTML source code.

Thank you!

**Comment by rikapo** [comment]
@szepeviktor Have you tried to turn off the `Remove XML instructions` option?

![image](https://user-images.githubusercontent.com/12181206/131315543-bdc023a3-d764-451a-b233-071f4507e645.png)

**Comment by szepeviktor** [comment]
@rikapo Thank you!
The **downloaded** .svg file still does not have the XML header.

**Comment by rikapo** [comment]
@szepeviktor Oh, I see. You need to add XML instruction to a svg that doesn't have it, right?
Unfortunately, this project is just GUI for [SVGO](https://github.com/svg/svgo) and SVGO doesn't have any plugins about **adding** XML instruction.
I think you can open this issue at [SVGO](https://github.com/svg/svgo) project if you want to.

**Comment by TrySound** [comment]
SVGO is an **O**ptimizer. xml instruction is not necessary to use .svg files in many environments. If you need to add somethinng use svgo package directly and write custom plugin like this

```js
const addXmlInstructionPlugin = {
  type: 'visitor',
  name: 'add-xml-instruction',
  fn: () => {
    let hasXmlInstruction = false;
    return {
      instruction: {
        enter: node => {
          if (node.name === 'xml') {
            hasXmlInstruction = true;
          }
        }
     },
      root: {
        exit: node => {
          if (hasXmlInstruction === false) {
            node.children.push({
              type: 'instruction',
              name: 'xml',
              value: 'version="1.0" encoding="utf-8"',
            })
          }
        }
      }
    }
  }
}
```

**Comment by szepeviktor** [comment]
Thank you.
