### ISSUE TITLE
Easily Copy Out of Code View

### ISSUE THREAD

**Issue by shshaw** [jakearchibald/svgomg#22]
I love using the Paste Markup & Code View to quickly optimize SVGs without having to mess with a lot of files. However, when I toggle over to Code View, I want to hit CMD + A to select all and copy the code out, but I always end up text from the UI:

```
Open SVG
Paste markup
Demo
Contribute
About
Powered by the incredible SVGO


IMAGE
CODE
765 bytes - 12.97% saving
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"> ... </svg>
```

Any way to make it easier to copy the code view? Two suggestions:

* Make Code View a textarea or iframe so it's isolated from the rest of the document
* Add `user-select: none` to all the UI elements to prevent the text from being selected.

**Comment by Tigt** [comment]
Adding the `contenteditable` attribute to the code's holder element seems like the simplest way of accomplishing this, and might also be nice to make a few edits the control panel can't.

**Comment by shshaw** [comment]
Ah, good idea! Adding it to `.code-output` in DevTools gives the desired result.

**Comment by jakearchibald** [comment]
Good idea, will play with this

**Comment by s10wen** [comment]
:+1:

**Comment by elwinschmitz** [comment]
:+1: 
Adding `spellcheck="false"`, would make the code output have less squiggly red lines.

And while we're at it: `autocomplete="off" autocorrect="off" autocapitalize="off"` would help if SVGOMG would support inline-editing of the SVG code...
