### ISSUE TITLE
Update Prism/revisit rollup fixes

### ISSUE THREAD

**Issue by XhmikosR** [jakearchibald/svgomg#252]
Not sure if this is still needed with the latest prismjs. There's also a build warning:

```
Sourcemap is likely to be incorrect: a plugin (rollup-fixes) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```

BTW I was wondering, shouldn't we load the Prism languages we only need?

**Comment by XhmikosR** [comment]
The included languages should be OK as it is.

Another thing worth revisiting is the Prism hack. There must be another way to do things without overriding the `message` listener.

**Comment by jakearchibald** [comment]
Fixed in https://github.com/jakearchibald/svgomg/pull/218
