### ISSUE TITLE
Improssible to zoom on mobile/with a touch device

### ISSUE THREAD

**Issue by XhmikosR** [jakearchibald/svgomg#305]
It seems that currently zooming in/out with a pinch on mobile or a touch device is not possible.

**Comment by jakearchibald** [comment]
It's working for me. Can you give me more details? (Browser + version at least)

**Comment by XhmikosR** [comment]
Hmm, it seems it's broken only on my xmr-dev branch. I'll close this and try to pinpoint the issue there.

**Comment by XhmikosR** [comment]
Freaking `reduce` 😛 I pinpointed the cause, all good.
