### ISSUE TITLE
Add option 'Remove hidden layer elements'

### ISSUE THREAD

**Issue by s10wen** [jakearchibald/svgomg#32]
I noticed when exporting from Illustrator `.st1{display:none;}`.

If there's hidden layers it outputs the code in the SVG and then hides them. I understand that sometimes this might be useful, but it would be nice to have an option to remove them if possible.

E.g.
Toggling the option on would remove any code classes with `display: none` along with associated tag.

Hopefully that makes sense. I'm interested to know what you think, or if there's another solution to this issue that I've missed.

**Comment by Tigt** [comment]
It's better to suggest optimizations like that to the core engine at [svg/svgo](https://github.com/svg/svgo), since it's what powers SVGOMG.

**Comment by s10wen** [comment]
@Tigt ah ok, cheers, done https://github.com/svg/svgo/issues/437
