### ISSUE TITLE
Allow decimal precision to go to 0

### ISSUE THREAD

**Issue by tigt** [jakearchibald/svgomg#35]
I've gone so far as to make a bookmarklet to hack this in, since every once in a while you get some SVGs that really benefit from dropping the decimal points.

**Comment by redpik** [comment]
:+1:

**Comment by waldyrious** [comment]
:+1:

**Comment by DanReyLop** [comment]
The change is trivial, once https://github.com/svg/svgo/pull/480 gets merged we can bump SVGO dependency and make the change.

**Comment by Sphinxxxx** [comment]
@tigt - Could you please post your bookmarklet code? I'm sure a lot of people would find it useful!

**Comment by tigt** [comment]
Unfortunately, it's since stopped working; SVGOMG shows an error I can't figure out. You can adjust `<input name="floatPrecision" type="range">`'s `value` manually if you want to try.

**Comment by Sphinxxxx** [comment]
This was fixed with https://github.com/jakearchibald/svgomg/pull/117 (through commit https://github.com/jakearchibald/svgomg/commit/c5da12c59a810b05e94f80193251d73d1c66040d), so this issue (and #92) can be closed now.

**Comment by jakearchibald** [comment]
Cheers! I need to do a sweep of the issues and find out what's covered.
