### ISSUE TITLE
ARIA attributes are removed as "unknown"

### ISSUE THREAD

**Issue by adactio** [jakearchibald/svgomg#36]
Currently SVGOMG removes ARIA attributes such as "aria-labelledby" if the "Remove unknowns and defaults" option is enabled.

A pattern that I use is to label the contents of an SVG image with its title element:

```
<svg aria-labelledby="image-title">
<title id="image-title">Title Of This Image</title>
....
</svg>
```

Reference: https://www.paciellogroup.com/blog/2013/12/using-aria-enhance-svg-accessibility/

Would it be possible to add attributes beginning with "aria-" into the "known" category?

(there may be some knock-on effects for the "Clean IDs" option: if an ID is being referenced by an ARIA attribute, it shouldn't be removed)

**Comment by jakearchibald** [comment]
I think this may be an SVGO issue. I'll open a ticket with them if I don't find a way to expose it.

**Comment by KaraAJC** [comment]
I just came across this as I noticed the tool also recommends removing title and description from the SVG, without reasoning for why that should happen. To my understanding, it's important to have a title and description tag for a11y purposes. http://web-accessibility.carnegiemuseums.org/code/svg/

**Comment by XhmikosR** [comment]
IIRC there's an upstream issue about this. If not, there should be one there and not in this repo, since svgomg is basically an svgo app.

**Comment by XhmikosR** [comment]
I'm going to close this since it's an svgo issue. That being said, I quickly tested the latest version and it seems that some if not all `aria` attributes are kept now.

If not, someone should open an upstream issue.
