### ISSUE TITLE
[Question] serving svgomg as a demo app for e2e testing

### ISSUE THREAD

**Issue by pavelfeldman** [jakearchibald/svgomg#373]
Hi folks, I'm working on [Playwright](https://playwright.dev) and I was looking for a demo project that we could use to show case Playwright capabilities. The idea is to create a repo with a couple of dozen of tests that target some nice app and test it. Svgomg seems to be a great match. We obviously don't want to target the live version of the site, so it would be something like a snapshot of svgomg running say at https://svgomg.playwright.dev. We would make sure it is clear that we serve a fork of your app, link to the original and claim that this is used as a show-case only, making sure nobody confuses it with the real thing. But it would still be a snapshot of your code serving off playwright subdomain. So I was wondering if you would be cool with that.

License-wise, we should be good, credit-wise, we'll make sure it is obvious that we are a clone for testing purposes. But I thought that I should still ask nicely!

**Comment by jakearchibald** [comment]
Yeah, that's fine. I did a similar thing with the Preact site when demoing Shared Element Transitions - https://preact-with-nav-transitions.netlify.app/ - something like the banner across the top of the page would be good.
