### ISSUE TITLE
Do not delete line breaks for a better code repository diff

### ISSUE THREAD

**Issue by math-GH** [jakearchibald/svgomg#375]
Hi,

I like SVGOMG very much. Its results are awesome.

I used it also to compress SVG files for the app FreshRSS (see: https://github.com/FreshRSS/FreshRSS/pull/4004#discussion_r782911625). The comment of @Frenzie is a interesting point: Line breaks/Newlines help for better code change diffs.

With SVGOMG the SVG files are always without newlines (also, when all options are disabled).

It would be very useful to disable this optimization.

What do you think?

**Comment by XhmikosR** [comment]
You can keep the whitespace by enabling the prettify option.
