### ISSUE TITLE
Why online optimizer adds extra code to svg after optimization.?

### ISSUE THREAD

**Issue by Ihornechypor** [jakearchibald/svgomg#377]
Why online optimizer adds extra code to svg after optimization.?
https://jakearchibald.github.io/svgomg/
https://ibb.co/Lr0m96T

**Comment by TrySound** [comment]
@Ihornechypor What's your source svg?

**Comment by Ihornechypor** [comment]
![section-contest-blop-steps-mob](https://user-images.githubusercontent.com/16295208/151392853-7fe1702e-0e60-4da6-a6d6-85d43fec6284.svg)
![section-contest-blop-steps-mob_after](https://user-images.githubusercontent.com/16295208/151392876-01d1a53a-e2d2-48ac-b61a-65fd24eb2faf.svg)

**Comment by Ihornechypor** [comment]
@TrySound  it is ok. Problem was on my side
