### ISSUE TITLE
Add option (or default) to remove `xml:space` as it is deprecated

### ISSUE THREAD

**Issue by perpetual-education** [jakearchibald/svgomg#379]
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xml:space

_<svg viewBox="0 0 10 10" `xml:space="preserve"` ..._

**Comment by XhmikosR** [comment]
Upstream PR https://github.com/svg/svgo/pull/1660

**Comment by XhmikosR** [comment]
Closing for now. If it's implemented upstream, we can update svgo and add the plugin here too.
