### ISSUE TITLE
Can this be a npm package?

### ISSUE THREAD

**Issue by jetrotal** [jakearchibald/svgomg#384]
I'm working on this on codepen: https://codepen.io/jetrotau/pen/popOqrV
![image](https://user-images.githubusercontent.com/45118493/163899324-1e035737-b85f-4c6d-9575-28af34380f78.png)

And codepen supports importing npm packages like this:
`import * as svgo from "https://cdn.skypack.dev/svgo@2.7.0";`

I'd love to be able to import svgomg library on codepen or anywhere like this.

thanks in advance!

**Comment by TrySound** [comment]
Here's browser compatible version
https://unpkg.com/browse/svgo@3.0.2/dist/svgo.browser.js
