### ISSUE TITLE
Feature request: An option to remove comments

### ISSUE THREAD

**Issue by babakfp** [jakearchibald/svgomg#386]
Hi
Can we please have an option to remove the comments `<!-- -->` from the SVG file?
Thanks

**Comment by TrySound** [comment]
SVGOMG have such an option. Or do you have something else in mind?

<img width="323" alt="image" src="https://user-images.githubusercontent.com/5635476/196137152-0b9707b3-2454-46f0-941c-892f48f52728.png">

**Comment by babakfp** [comment]
Hi
It doesn't work.
1. Go here https://fontawesome.com/icons/house?s=solid&f=classic
2. Download the SVG file
3. Import it into SVGOMG
4. Turn on the Remove comments option
5. Copy the result and you will see the comment is still remaining.

**Comment by XhmikosR** [comment]
Closing per https://github.com/svg/svgo/issues/1686
