### ISSUE TITLE
Remove unknowns & defaults should also works within 𝚜𝚝𝚢𝚕𝚎 attribute

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [jakearchibald/svgomg#408]
Although SVGOMG have an “Remove unknowns & defaults” option, it doesn’t works with CSS properties in `style` attribute, instead, it must works with “Style to attributes” option. If this option could be able to clean up CSS styles as well, that would be more useful for SVGs created by major SVG editors.

This can be reproduced with https://upload.wikimedia.org/wikipedia/commons/archive/3/30/20200701055512%21PatriarchsCross.svg

**Comment by XhmikosR** [comment]
Such requests should be made upstream in svgo; SVGOMG is mostly an SVGO wrapper.

**Comment by KrasnayaPloshchad** [comment]
I reported.
 https://github.com/svg/svgo/issues/1706

**Comment by XhmikosR** [comment]
Closing the issue here since there's an upstream issue.
