### ISSUE TITLE
Your github pages is down

### ISSUE THREAD

**Issue by dsandstrom** [jakearchibald/svgomg#41]
![00000153](https://cloud.githubusercontent.com/assets/1400414/12996725/45178bc8-d0e7-11e5-8165-81584a9e0b47.png)

**Comment by dsandstrom** [comment]
Sorry to bug you again.  Are you planning on resurrecting your github pages version or should we just use local servers?

**Comment by jakearchibald** [comment]
It's working for me. If you shift+reload, do you get the site? What link are you using?

**Comment by dsandstrom** [comment]
Thanks for replying.

Strange, a browser restart fixed it for me.  Not sure what happened, maybe a bad cache.  Closing.
