### ISSUE TITLE
Incorrect direction zoom

### ISSUE THREAD

**Issue by melstone** [jakearchibald/svgomg#45]
After downloading the SVG zoom direction when non-standard scroll mouse.

**Comment by stuartlangridge** [comment]
Annoyingly, https://github.com/w3c/uievents/issues/57 shows no consensus, and `MouseEvent.webkitDirectionInvertedFromDevice` was never implemented outside WebKit, so there doesn't seem to be a way for a page to know the user's system scroll settings. It is quite disorienting that SVGOMG zooms in the wrong direction (although obviously it's easy to work out what to do in response).

**Comment by XhmikosR** [comment]
Closing this in favor of #19.
