### ISSUE TITLE
Cannot go back to Image tab in Firefox

### ISSUE THREAD

**Issue by fvsch** [jakearchibald/svgomg#53]
Steps to reproduce:
1. Open https://jakearchibald.github.io/svgomg/ in Firefox
2. Select Paste Markup and paste a simple SVG document
3. Switch to the Code tab.
4. Click the Image tab.

Results: the tab itself gets focused but the Code content remains.

![svgomg-fx-tab-bug](https://cloud.githubusercontent.com/assets/243601/17273137/7917b73c-56ab-11e6-8ecb-3345d065af1e.png)

Note: I have this issue systematically, _but_ when keeping the Firefox devtools open to look at what is happening, it ends up working most of the time. With the devtools closed, I’ve seen it working a few times, but not often. It’s kind of an intermittent bug.

Tested today on Firefox 48 and 49 on OSX, but I’ve had this issue on Win10 as well I think, and for a very long time (maybe since the first release of SVGOMG).

**Comment by tigt** [comment]
This seems fixed on FF 59.0a1

**Comment by jakearchibald** [comment]
Whoop!

**Comment by NotWoods** [comment]
Broken again in Firefox 70 ☹️ 

Steps to reproduce:
- Open a custom SVG (the demo seems to work fine)
- Select the Markup tab
- Try to select the Image tab, but you're stuck on the Markup tab.
