### ISSUE TITLE
Drag & drop overlay not appearing a second time

### ISSUE THREAD

**Issue by moesphemie** [jakearchibald/svgomg#57]
I really enjoy the drag and drop function but when it comes to the situation where you have two or more graphics you want to send through this brilliant machine i always have to reload the browser to be able to drag & drop again. Could you implement this functionality to work every time when clicking on the menu-icon, not only after the app loads?

**Comment by jakearchibald** [comment]
Drag & drop is always supported

**Comment by moesphemie** [comment]
ah i see now, i missed the black overlay and the text "Drag & Drop" when uploading another svg

**Comment by jakearchibald** [comment]
That's worth fixing. Ta!
