### ISSUE TITLE
What does the 'M' stand for?

### ISSUE THREAD

**Issue by jakearchibald** [jakearchibald/svgomg#6]
SVGOMG - the SVGO stands for SVGO, obviously. The G stand for GUI. The M?

**Comment by mikestreety** [comment]
Modification?

Because its a GUI to modify SVGO....

**S**calable 
**V**ector 
**G**raphics
**O**ptimizer
**M**odification
**G**UI

**Comment by fvsch** [comment]
Right now it kind of stands for Material, right? :)

Though it could stand for:

- Modern
- Movable
- Mindful
- Modest
- Marketable
- Makeshift
- Mighty
- Mesmerizing
- Marvelous
- Magnificent
- Miraculous
- Momentous
- (yeah there are plenty of M- superlatives)
- Merciful (I like this one :))
- aMazing
- Missing (SVGO's Missing GUI)
- Mad
- Magical
- Machiavellian
- Mini(malist) (probably won't qualify for this one?)
- Mere (as in, this is but a mere GUI for SVGO)

Pick one.

**Comment by Tigt** [comment]
Scalable Vector Graphics're Obese? Minify & Gzip!

**Comment by Tigt** [comment]
But for real, I dig "Missing" too.

**Comment by waldyrious** [comment]
:+1: for SVGO's Missing GUI too :)

**Comment by jakearchibald** [comment]
"Scalable Vector Graphics're Obese? Minify & Gzip!" is amazing, but going to go for "missing"
