### ISSUE TITLE
Remember config

### ISSUE THREAD

**Issue by math2001** [jakearchibald/svgomg#60]
Salut!

I use `SVGOMG` every single day, it is just great! But each time, I have to re-set my config. I don't thing it would be really hard to implement a **cookie system** that would **remember** our config.

Math

**Comment by jakearchibald** [comment]
If it's easy, I'd gladly accept a PR for this. I agree that it'd be a useful feature.

**Comment by math2001** [comment]
I looked a bit at your code, but I don't understand anything, the `js/page.js` that you're loading doesn't even exist. I don't know what technologie you're using, but, for sure, I don't know how to use it. So, I'm not going to code this. Sorry.
