### ISSUE TITLE
Bulk edit

### ISSUE THREAD

**Issue by victorwestmann** [jakearchibald/svgomg#64]
Is it possible to batch optimize SVG files with this tool?

**Comment by szepeviktor** [comment]
You may use the tool it built on
https://github.com/svg/svgo

**Comment by mspanish** [comment]
I realize I can use svgo to do this, but do you have a way to export the config settings you've set in your tool, and use them in the other?

**Comment by szepeviktor** [comment]
I think configuration here means *loading a plugin*
See https://github.com/jakearchibald/svgomg/blob/9d09a4d255b0daa2cd39fdde59553d5154e770f1/src/js/svgo-worker/index.js#L11

**Comment by mspanish** [comment]
thank you!

**Comment by sompylasar** [comment]
I've started working on this in my fork, but from the first glance into the code, this requires rework of certain internals, as well as the UI, because they are now hard-wired to handle just one file.

**Comment by mspanish** [comment]
i am very interested in any updates on this! The product of  this app is just way better than what I get using svgo alone.

**Comment by sompylasar** [comment]
The magic happens here, in the `bulk-edit` branch: https://github.com/jakearchibald/svgomg/compare/master...sompylasar:bulk-edit

Multi-file opening, drag-n-drop, and processing works. Next is make the UI show multiple files and allow to copy/download them.

**Comment by mspanish** [comment]
i don't even need UI - doing all behind scenes :)

**Comment by sompylasar** [comment]
@mspanish How do you download the results without a UI?

**Comment by mspanish** [comment]
Ah for this app I have to download the result 1 at a time. For my own process, I run the SVG folders through SVGO in a Node.js app I built.  What I'd love is to use svgomg inside my own process to process the SVGs.

**Comment by sompylasar** [comment]
@mspanish OK. That's probably not what this issue is about... What you want is export the SVGO plugins and their settings from SVGOMG as a standalone Node.js module to require from your Node.js app.

What I'm doing for this repo is providing the "missing GUI" for the bulk SVGO processing. In the end, you'll be able to download all at once (I haven't decided how yet, most likely as a ZIP archive).

**Comment by mspanish** [comment]
as long as I can do a batch of SVGs, I don't really care if I have to use a GUI, so this would be OK for now. My node.js is only local, used to produce content for a static app.

**Comment by sompylasar** [comment]
Code-complete, tested in Chrome. PR: https://github.com/jakearchibald/svgomg/pull/98

**Comment by mspanish** [comment]
very cool I will try it out!

**Comment by mspanish** [comment]
how do I download this code?

**Comment by sompylasar** [comment]
@mspanish 
```
git clone https://github.com/sompylasar/svgomg.git ./svgomg-sompylasar
cd ./svgomg-sompylasar
git checkout --track origin/bulk-edit
npm install
npm run serve
```

**Comment by mspanish** [comment]
you are the man, gracias.
