### ISSUE TITLE
Paste markup doesn't work?

### ISSUE THREAD

**Issue by dandv** [jakearchibald/svgomg#65]
After clicking on Paste markup, it appears that the user is supposed to paste the markup in the "Paste markup" menu item itself:

![image](https://cloud.githubusercontent.com/assets/33569/19096343/8a8778ee-8a50-11e6-9a96-c2259b5b88ad.png)

Maybe the drawer doesn't close?

**Comment by jakearchibald** [comment]
> After clicking on Paste markup, it appears that the user is supposed to paste the markup in the "Paste markup" menu item itself

Yes that's right. Have you tried pasting markup?

**Comment by dandv** [comment]
Yes. If I paste invalid markup and press Enter, there's no error message.

If I paste the markup below, the drawer closes automatically (I don't even need to press Enter - nice), there's no Image, I do see the Code, but when I tab back to Image then to Code, the Code tab is empty.

```svg
<svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet"><g><path d="M9 3L7.17 5H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2h-3.17L15 3H9zm3 15c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5zm0-1l1.25-2.75L16 13l-2.75-1.25L12 9l-1.25 2.75L8 13l2.75 1.25z"></path></g></svg>
```

**Comment by jakearchibald** [comment]
Ah, looks like the namespace is missing. This works:

```svg
<svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg">
  <g>
    <path d="M9 3L7.17 5H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2h-3.17L15 3H9zm3 15c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5zm0-1l1.25-2.75L16 13l-2.75-1.25L12 9l-1.25 2.75L8 13l2.75 1.25z"></path>
  </g>
</svg>
```
