### ISSUE TITLE
https://jakearchibald.github.io/svgomg/ site is not generating SVGs

### ISSUE THREAD

**Issue by tcaddy** [jakearchibald/svgomg#67]
FYI: Since yesterday, I have been unable to use https://jakearchibald.github.io/svgomg/ to generate SVG files.  The site will load, but nothing happens when you place a SVG file there.

Installing and running this app locally still works.

**Comment by tyrann0us** [comment]
@jakearchibald, do you mind taking a look at this issue?
Thanks!

**Comment by jakearchibald** [comment]
What browser & OS are we talking about?

**Comment by tyrann0us** [comment]
Windows 10 (Anniversary Update), Chrome 54.
When pasting SVG markup the blue loading spinner next to the field keeps spinning forever.

**Comment by jakearchibald** [comment]
I can recreate & will investigate when I get a moment.

It works in Chrome Canary, so I suspect some kind of Chrome bug that's already been fixed.

**Comment by tcaddy** [comment]
FYI: The site started working for me a few days ago.  Also, while it wasn't working, I assumed a backend process wasn't running because when I ran the project locally (with the same version of Google Chrome), it worked OK.

**Comment by jakearchibald** [comment]
Yeah, I similarly cannot recreate the issue locally. Definitely not a server issue since it's just a static host. Digging in…

**Comment by jakearchibald** [comment]
Also works fine in incognito.

**Comment by tcaddy** [comment]
Do you mean that there is no server-side processing of SVG images?  Does everything happen in javascript on the client side?

**Comment by jakearchibald** [comment]
@tcaddy yeah, it's all clientside (and works offline).

Found the bug. If you'd selected "show original" then left the site, that setting was remembered. Then when you returned to the site, the code was waiting for the SVG to be compressed before hiding the main menu, but if you had "show original" selected that never happened.

**Comment by jakearchibald** [comment]
Thanks for reporting!
