### ISSUE TITLE
`Load failed: Text data outside of root node.` when pasting from Illustrator

### ISSUE THREAD

**Issue by alexzaworski** [jakearchibald/svgomg#68]
A recent (ish? it's been a while) update causes `Load failed: Text data outside of root node` to be thrown when pasting directly from Illustrator (ie copying from an artboard). This error is _technically_ correct, since Illustrator prepends a comment when copy/pasting SVG: 

```<!-- Generator: Adobe Illustrator 20.1.0, SVG Export Plug-In  -->```

That said, it would be nice if instead of throwing an error and canceling the paste process you instead 

- a) Threw a warning that some text was stripped but continued with loading
- b) Threw an error but allowed the user to continue anyways (stripping the excess text)

**Comment by alexzaworski** [comment]
I messed around with this a bit and it doesn't seem to be solely an issue of stripping the comment.

Pasting directly from illustrator breaks, but pasting into a text editor _first_ and then pasting _the exact same text_ into SVGOMG works fine. Not sure if there if there's some formatting data from Illustrator that comes along for the ride or what.

**Comment by jerone** [comment]
Maybe line-endings...

**Comment by alexzaworski** [comment]
I thought that may be the case but wouldn't it be caught by `trim()`? Here's the current handler for pasting: 
```
_onTextInputChange(event) {
    var val = this._pasteInput.value.trim();

    if (val.indexOf('</svg>') != -1) {
      this._pasteInput.value = '';
      this._pasteInput.blur();

      this._pasteLabel.appendChild(this._spinner.container);
      this._spinner.show();

      this.emit('svgDataLoad', {
        data: val,
        filename: 'image.svg'
      });
    }
  }
```

**Comment by alexzaworski** [comment]
Figured it out, Illustrator is appending a null character which isn't caught by `trim()` — I'll submit a PR

**Comment by XhmikosR** [comment]
Can someone upload a file that has this issue?

I start to think this should be handled in svgo if it's not already.

**Comment by alexzaworski** [comment]
> Can someone upload a file that has this issue?
> 
> I start to think this should be handled in svgo if it's not already.

Hi :) I submitted this way back in 2016 and still use SVGOMG for the same workflow that this bug broke. More recent versions of illustrator don't have this null terminator problem so it may be tough to reproduce organically.

To clarify it was never an illustrator _file_ that caused the issue, it was copying and pasting directly from illustrator into SVGOMG.

**Comment by XhmikosR** [comment]
I know a lot of time has passed :)

That being said, I'm trying to find a way to reproduce the issue so that I test if it still happens.

**Comment by alexzaworski** [comment]
Here are some steps I took to reproduce this problem today:

- Create some test svg `$ echo '<svg/>' >> test.svg`
- Try uploading to svgomg (should work fine)
- Append null terminator: `$ cat test.svg >> broken.svg && echo '\0' >> broken.svg`
- Try uploading to svgomg (should throw)
- Run trim/replace from PR `$ node -e 'console.log(require("fs").readFileSync("./broken.svg").toString().trim().replace(/\0+$/g, ""))' >> fixed.svg`

Hopefully this helps :) Though again I don't really expect you'll encounter this in the wild and the fact that invalid characters were being appended is really Illustrator's fault.

**Comment by jakearchibald** [comment]
It seems like this is fixed in Illustrator now?
