### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by rugk** [jakearchibald/svgomg#74]
Maybe some tooltips for the circle buttons would be useful as I still don't get what the "copy button" is for. Where copies it data to/from?

**Comment by jakearchibald** [comment]
It copies to your clipboard

**Comment by rugk** [comment]
Ah all right. In any case either a visual feedback for this particular button would nice ('svg copied!') or as I suggested add tooltips, so one knows what the button does.

**Comment by anyotherway** [comment]
http://www.dottielocks.art
dottie's got me going on SVG as PNG stopped working nicely for this data model a few months ago. Anyway, how do you tooltip SVG buttons here using HTML and CSS? Stu is super hush on this one, but hashed out a dozen new circle menus when i started dishing out possibilities. Which all seem to be meticulously unique transformed and transitioned tooltips for 43 buttons, unless... ? This highlights feed-out issues for all transform-transition models.

**Comment by CameronSamuels** [comment]
I was about to create an issue on this.

**Comment by XhmikosR** [comment]
@jakearchibald There are titles on the buttons already?

**Comment by jakearchibald** [comment]
Yep, this is fixed.
