### ISSUE TITLE
Inline styles may save space

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [jakearchibald/svgomg#77]
A document like this:

    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><style>.st0{fill:#020203;}</style><path class="st0" ...

May use up unnecessary space if the style is only used once. An option to inline styles should maybe be supported.

**Comment by jakearchibald** [comment]
This is more of a suggestion for https://github.com/svg/svgo

**Comment by strarsis** [comment]
Relevant svgo PR: https://github.com/svg/svgo/pull/592
