### ISSUE TITLE
Round/Rewrite Path ruins SVG

### ISSUE THREAD

**Issue by JoKalliauer** [jakearchibald/svgomg#79]
The option "Round/rewrite path" removes some lines/curves, some lines/curves are completely different place.
In the Attachment is the SVG before and after.

[ChangeRoundRewritePath.zip](https://github.com/jakearchibald/svgomg/files/746010/ChangeRoundRewritePath.zip)

**Comment by alexjlockwood** [comment]
This is likely a bug in svgo, I encourage you to report a bug there instead: https://github.com/SVG/svgo

**Comment by JoKalliauer** [comment]
Done:
[https://github.com/svg/svgo/issues/868](https://github.com/svg/svgo/issues/868)
