### ISSUE TITLE
Safari doesn't download SVG when download button is clicked

### ISSUE THREAD

**Issue by jakearchibald** [jakearchibald/svgomg#8]
because http://caniuse.com/#feat=download

Is there a workaround?

**Comment by CalebGrove** [comment]
+1

**Comment by jakearchibald** [comment]
I don't think there's a workaround :(

**Comment by Tigt** [comment]
You'd have to reflect it off an actual server with `application/octet-stream` set. It's a bit involved, though.

**Comment by jakearchibald** [comment]
Fixed in IE thanks to IE-prefixed API I didn't know about

**Comment by XhmikosR** [comment]
@jakearchibald I guess this can be closed after 6+ years 😛

**Comment by jakearchibald** [comment]
Yeah, this now works.
