### ISSUE TITLE
Round/rewrite Transform ruins SVG

### ISSUE THREAD

**Issue by JoKalliauer** [jakearchibald/svgomg#80]
The option "Round/rewrite Transform" cutes the picture with a high "resolution" to a smaller size
In the Attachment is the SVG before and after.
[CompareRoundRewiteTransforms.zip](https://github.com/jakearchibald/svgomg/files/746019/CompareRoundRewiteTransforms.zip)

**Comment by XhmikosR** [comment]
@jakearchibald this should be closed as it's an upstream issue (if still present in the latest svgo)

**Comment by TrySound** [comment]
@XhmikosR Nobody gonna open these issues in svgo. Please stop asking to close them. I'm looking into them when I have time.

**Comment by jakearchibald** [comment]
My bad, sorry

**Comment by XhmikosR** [comment]
Or you could move the repo under the same org so that you can move issues to the proper repo.

**Comment by TrySound** [comment]
I'm just helping not owning repo

**Comment by XhmikosR** [comment]
This doesn't seem to happen anymore. I tested v3.0.0 which is live, with the default settings.

@JoKalliauer please confirm and close the issue, otherwise please make an upstream issue.
