### ISSUE TITLE
Merge Path deletes arrows of line

### ISSUE THREAD

**Issue by JoKalliauer** [jakearchibald/svgomg#81]
Merge Path sometimes deletes some arrows at the end of a line
[MergePath.zip](https://github.com/jakearchibald/svgomg/files/752482/MergePath.zip)

**Comment by XhmikosR** [comment]
@jakearchibald this should be closed as it's an upstream issue (if still present in the latest svgo)

**Comment by TrySound** [comment]
Fixed
