### ISSUE TITLE
Can not download svg at Safari 10.0.2

### ISSUE THREAD

**Issue by JamesMatt** [jakearchibald/svgomg#82]
OS: MacOS 10.12.2
Browser: Safari 10.0.2

When svg has been compressed to complete, I can't download it. Please fix the compatibility issue, thanks!

![screenshot](https://cloud.githubusercontent.com/assets/25457860/22626535/a5d3b652-ebea-11e6-995e-cfb738884b58.png)

**Comment by XhmikosR** [comment]
@jakearchibald Safari 10 is not supported anymore and it seems to work on the latest version AFAICT so this can be closed?

**Comment by jakearchibald** [comment]
Agreed
