### ISSUE TITLE
Cannot optimize SVG [Minifying error]

### ISSUE THREAD

**Issue by mctep** [jakearchibald/svgomg#83]
Hello! Thank you for your job.

I try to optimize my SVG through https://jakearchibald.github.io/svgomg/

```xml
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 17.9 32.1">
  <path d="M16,32.1l1.9-1.9L3.8,16L17.9,1.9L16,0L0,16L16,32.1z"/>
</svg>
```

But it throws an error:

```
Minifying error: Cannot read property 'value' of undefined
```

**Comment by TadWohlrapp** [comment]
It works, when you add the width and height attributes:

```svg
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 17.9 32.1" width="17.9" height="32.1">
  <path d="M16,32.1l1.9-1.9L3.8,16L17.9,1.9L16,0L0,16L16,32.1z"/>
</svg>
```

**Comment by flibX0r** [comment]
Looks like it's the **Optimise single-path SVG** option when given an SVG with a single shape and no defined width or height (although it doesn't error with a circle or ellipse)

**Comment by alexjlockwood** [comment]
This plug-in has been removed in the latest release.

**Comment by lydenyardley** [comment]
Hello,

Absolutely LOVE your web app, and have used it quite a bit. Recently though, I've been getting the error defined in this Github issue. Here's an example SVG which is live on my website, and renders just fine in a browser (no issues reported in console either):
`<?xml version="1.0" encoding="UTF-8"?>
<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 499 499">
    <path d="M0 350V34c0-6 4-10 10-10h479c6 0 10 4 10 10v316H0z" fill="#435670"/>
    <path d="M320 472H178l10-72h122l10 72z" fill="#87A9BB"/>
    <path d="M350 470H148a6 6 0 100 12h202a6 6 0 100-12zm149-90v-30H0v30c0 11 9 20 20 20h459c11 0 20-9 20-20z" fill="#A7C0CD"/>
    <path d="M487 36H12v302h475V36z" fill="#fff"/>
    <path d="M232 173h-23v60h23v-60z" fill="#FFC34C"/>
    <path d="M203 132h-23v101h23V132z" fill="#A7C0CD"/>
    <path d="M173 106h-23v127h23V106z" fill="#FFC34C"/>
    <path d="M144 156h-23v77h23v-77z" fill="#A7C0CD"/>
    <path d="M114 183H92v50h22v-50z" fill="#FFC34C"/>
    <path d="M85 204H62v29h23v-29z" fill="#A7C0CD"/>
    <path stroke="#435670" stroke-width="12" stroke-linecap="round" d="M308 271h118m-83 29h48m-204 0H69m157-29H69"/>
    <path d="M367 124a56 56 0 1056 56h-56v-56z" fill="#FF8000"/>
    <path d="M406 140l-39 40h56c0-15-6-29-17-40z" fill="#FFC34C"/>
    <path d="M377 101v56l39-40a55 55 0 00-39-16z" fill="#A7C0CD"/>
    <path d="M236.3 58.8l-5.1 8.5v6.2h-2.3v-6.2l-5.2-8.5h2.6l3.7 6.4 3.8-6.4h2.5zm1.9 14.9c-1 0-1.7-.3-2.3-.9a3 3 0 01-.8-2.2c0-.9.3-1.6 1-2.1a5.6 5.6 0 012.2-1.2c1-.2 1.9-.4 2.8-.4 0-.8-.2-1.3-.5-1.6-.4-.3-.9-.5-1.6-.5-.4 0-.9 0-1.3.2a6.2 6.2 0 00-1.5.7l-.2-1.8a6.9 6.9 0 013.6-1c1.3 0 2.2.4 2.8 1 .6.8.9 2 .9 3.6V71.1c0 .3.2.5.3.6l.7.2h.3l-.3 1.8h-.4c-.8 0-1.3-.2-1.7-.4a2.4 2.4 0 01-.9-1 4 4 0 01-3.1 1.4zm.6-1.8c.4 0 .8 0 1.2-.3a3 3 0 001.1-.8v-2.4c-2.5 0-3.8.8-3.8 2.1 0 1 .5 1.4 1.5 1.4zm7-8.8h2l.1 1.4c1-1 2-1.6 3-1.6h.4l-.2 2.3a3.1 3.1 0 00-.8 0 2.8 2.8 0 00-2.2 1v7.3h-2.3V63zm15.6-5.4v15.8h-2l-.1-1a4 4 0 01-3 1.2 4.4 4.4 0 01-2.5-.7 4.8 4.8 0 01-1.7-2 6.2 6.2 0 01-.6-2.7c0-1 .2-1.9.6-2.7a4.4 4.4 0 014.2-2.7 4 4 0 013 1.1v-6.3h2.1zm-4.8 14.1c.8 0 1.5-.3 2-.9.6-.6.8-1.5.8-2.6 0-1-.2-2-.8-2.5a2.5 2.5 0 00-2-1c-.8 0-1.5.3-2 1a4 4 0 00-.8 2.5 4 4 0 00.7 2.5c.6.7 1.3 1 2.1 1zm9.8 1.9c-1 0-1.6-.3-2-.8a2.7 2.7 0 01-.7-1.8V57.7h2.2V71.3l.5.5h1l-.3 1.9h-.7zm7.1 0a6 6 0 01-3-.8 4.9 4.9 0 01-2-2 6 6 0 01-.6-2.7c0-1 .2-1.9.6-2.6a4.7 4.7 0 014.5-2.7c1.3 0 2.4.4 3.2 1.2a4.3 4.3 0 011.3 3.2c0 .4 0 .8-.2 1.2h-7.1c.1 1.2.5 2 1.1 2.5.7.5 1.5.8 2.4.8 1.1 0 2.2-.2 3-.7l.3 1.8a8 8 0 01-3.5.8zm1.7-6.7c0-.6-.2-1.2-.5-1.6-.4-.4-1-.6-1.7-.6-1.4 0-2.3.7-2.7 2.2h5zm6.9 5.9l-4.3-9.8h2.4l3 7.3L286 63h2.5L282 78.5h-2.3L282 73z" fill="#435670"/>
    <path d="M228.9 77.2h2.3c.6 0 1.1 0 1.6.3s.8.6 1 1.1a3.4 3.4 0 010 3.3c-.2.5-.5.9-1 1.1-.5.2-1 .4-1.6.4h-2.3V77zm2.3 5.4a2 2 0 001.6-.6c.4-.4.5-1 .5-1.7s-.1-1.3-.5-1.7c-.4-.5-1-.7-1.6-.7h-1.5v4.7h1.5zm7.4-5.4h.9v6.2h-.9V77zm8.2 6.3a3 3 0 01-1.5-.4 2.8 2.8 0 01-1.1-1.1c-.3-.5-.4-1.1-.4-1.7 0-.7.1-1.3.4-1.7a3 3 0 011.1-1.2c.5-.2 1-.4 1.7-.4a4.3 4.3 0 011.8.4l-.1.7a4.6 4.6 0 00-1.7-.3c-.5 0-1 .1-1.3.3a2 2 0 00-.7.9c-.2.4-.3.8-.3 1.3 0 .7.2 1.3.6 1.8.4.4 1 .6 1.8.6a3.3 3.3 0 001-.1V81h-1v-.8h1.8V83c-.2.2-.5.3-.9.4h-1.2zm6.6-6.3h.8v6.2h-.8V77zm6.8.7h-1.8v-.8h4.4v.8H261v5.5h-.8v-5.5zm9.5 3.8h-2.4l-.6 1.7h-.9L268 77h1l2.2 6.3h-1l-.5-1.7zm-.3-.8l-1-2.6-.8 2.6h1.8zm5.8-3.8h.9v5.5h2.8v.8h-3.7V77z" fill="#000" fill-opacity=".9"/>
    <path d="M223.7 67.5l-5.2-8.7H213l5.3 8.7v6h5.4v-6zM215.7 67.5v6h-5.4v-6h5.4z" fill="url(#paint-gradient)"/>
    <defs>
        <linearGradient id="paint-gradient" x1="1%" y1="1%" x2="100%" y2="100%" gradientUnits="objectBoundingBox">
            <stop stop-color="#FFC34C"/>
            <stop offset=".5" stop-color="#FF8000"/>
            <stop offset="1" stop-color="#C75300"/>
        </linearGradient>
    </defs>
</svg>`

Can you advise?

**Comment by lydenyardley** [comment]
A-ha! Figured it. By going through the settings one-by-one... it was when I turned off 'Remove XML instructions' that I get the error:

`Minifying error: Cannot read property 'splice' of undefined`

Can you check into that. I don't see why it should be a problem...
