### ISSUE TITLE
Option to create unique ID's

### ISSUE THREAD

**Issue by timroeleveld** [jakearchibald/svgomg#91]
When inlining multiple svg's on a web page there will be masking problems because of duplicate ID's. An option to create unique ID's would be very helpful. An unique ID could be a string of 10 characters or so.

**Comment by strarsis** [comment]
@timroeleveld: svgo release contains the inlineStyles and prefixIDs plugins now.

**Comment by benjaminpayoux** [comment]
Hello,

Thank you for this awesome tool. It helps me a lot for integrating clean svgs into my UI.
Unfortunately, sometimes, I cannot make it work as I would.

For instance, when pasting this markup:

`
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24"><defs><path d="M13.584 0c1.624.003 2.304.013 2.985.038l.217.008.584.026c1.277.058 2.149.261 2.912.558a5.88 5.88 0 012.124 1.383 5.88 5.88 0 011.384 2.125c.297.763.5 1.635.558 2.912.048 1.066.066 1.527.07 3.537l.001.513v2.304c-.005 2.01-.023 2.471-.071 3.537-.059 1.277-.261 2.15-.558 2.912a5.88 5.88 0 01-1.384 2.125 5.88 5.88 0 01-2.124 1.384c-.763.296-1.635.499-2.912.557-1.066.049-1.528.066-3.537.071h-.513l-.281.001h-1.51l-.514-.001c-2.01-.005-2.47-.022-3.537-.07-1.277-.06-2.148-.262-2.912-.558a5.88 5.88 0 01-2.124-1.384 5.88 5.88 0 01-1.384-2.125c-.296-.763-.5-1.635-.557-2.912-.051-1.108-.068-1.563-.072-3.785v-2.32c.003-1.453.01-2.15.03-2.77l.016-.432C.482 7.452.49 7.263.5 7.05c.058-1.277.26-2.15.557-2.912a5.88 5.88 0 011.384-2.125A5.88 5.88 0 014.566.63C5.33.333 6.201.13 7.478.072l.585-.026.432-.015C9.114.01 9.811.003 11.265 0zm-.02 2.162h-2.28c-1.593.002-2.252.012-2.92.036l-.211.008-.576.025c-1.17.054-1.805.249-2.228.413-.56.218-.96.478-1.379.898-.42.42-.68.819-.897 1.379-.164.423-.36 1.058-.413 2.227l-.026.576-.008.212c-.024.667-.033 1.327-.035 2.92v2.279c.003 2.18.019 2.612.069 3.708.053 1.17.249 1.805.413 2.227.217.56.477.96.897 1.38.42.42.82.68 1.38.897.422.164 1.057.36 2.227.413l.576.025.212.008c.667.025 1.326.034 2.92.036h2.279c2.18-.003 2.611-.019 3.707-.069 1.17-.053 1.805-.249 2.228-.413.56-.218.96-.478 1.38-.897.419-.42.679-.82.897-1.38.164-.422.36-1.058.413-2.227.05-1.096.065-1.528.069-3.708v-2.279c-.003-1.593-.012-2.253-.036-2.92l-.008-.212a114.24 114.24 0 00-.025-.576c-.054-1.17-.25-1.804-.413-2.227a3.718 3.718 0 00-.898-1.38c-.42-.42-.82-.68-1.38-.897-.422-.164-1.057-.36-2.227-.413-1.096-.05-1.527-.066-3.707-.069zm-1.14 3.674a6.16 6.16 0 110 12.32 6.16 6.16 0 010-12.32zm0 2.161a3.999 3.999 0 100 7.997 3.999 3.999 0 000-7.997zm6.403-3.844a1.44 1.44 0 110 2.879 1.44 1.44 0 010-2.88z" id="a"/></defs><g transform="translate(-.429)" fill="none" fill-rule="evenodd"><mask id="b" fill="#fff"><use xlink:href="#a"/></mask><g mask="url(#b)"><path fill="#2A2830" d="M-57.429-56.571H82.285V83.143H-57.429z"/></g></g></svg>
`

I do not know how to "unduplicate the IDs" of the masks.
I tried to toggle all the options to see if something changed but without success.

Is there something I misunderstood ?

Thanks for your replies.

**Comment by strarsis** [comment]
@benjaminpayoux: For this the [`prefixIds`](https://github.com/svg/svgo/blob/master/plugins/prefixIds.js) `svgo` plugin would be the right candidate. It prefixes the `class`es and `id`s of all elements, effectively namespacing the SVG.

**Comment by benjaminpayoux** [comment]
Yes that's what I thought but I could not find it in the GUI.

Can you confirm that there is no toggle to do that ?

**Comment by strarsis** [comment]
@benjaminpayoux: Can't find a "prefix IDs" option on https://jakearchibald.github.io/svgomg/, so yes, it is still missing in the UI.

**Comment by AttackXiaoJinJin** [comment]
> @benjaminpayoux: Can't find a "prefix IDs" option on https://jakearchibald.github.io/svgomg/, so yes, it is still missing in the UI.

so when add a "prefix IDs" option on https://jakearchibald.github.io/svgomg/ , it would be very helpful for me!

**Comment by guyinpv** [comment]
Is there no way to help avoid duplicate IDs across many SVGs? 
It would be much better if there was an option to assign random ID numbers or a timestamp or a custom prefix of our choosing, so that multiple SVGs on a single page won't overlap styles. 

In my case there are definitions for gradients that use IDs and if I optimize just two different SVGs on the same page, the styles will break. I don't see any way to help randomize or make IDs more unique.

**Comment by WebWorkingMan** [comment]
I agree 100% with the previous speakers. Unfortunately, I have also just been confronted with the same situation. It would be really helpful and would have saved me a few headaches. 

BTW, why is this issue closed?
