### ISSUE TITLE
Set minimum of precision to 0

### ISSUE THREAD

**Issue by crantisz** [jakearchibald/svgomg#92]
Change 
`<input type="range" min="1" max="8" step="1" value="3" name="floatPrecision" class="">`
to
`<input type="range" min="0" max="8" step="1" value="3" name="floatPrecision" class="">`
because sometimes whole number needs

**Comment by Sphinxxxx** [comment]
Sadly, that will only throw an error in SVGO later on:

    Minifying error: toFixed() digits argument must be between 0 and 20

Related issue: #35
