### ISSUE TITLE
Results better here than via svgo in Node.js - doing anything different?

### ISSUE THREAD

**Issue by mspanish** [jakearchibald/svgomg#95]
The results I get via your web app are fantastic. When I try running the same SVGs through svgo via Node.js, they are not as good. I've tried using the exact same settings - but are you doing something else to help your process come out better? 

If anybody has this exact app in a form that can accept folders or batch  - I'd love to know about it! Thanks for the lovely tool.

**Comment by 4muzar** [comment]
Hm, I usually have the opposite result :/
@mspanish May you show an example files to demonstrate it?

**Comment by mspanish** [comment]
sorry I don't have one on hand - the batch tool is very cool though, you should try it out https://github.com/jakearchibald/svgomg/pull/98

**Comment by TrySound** [comment]
Latest SVGO is landed to SVGOMG
