### ISSUE TITLE
Minifying error when "Optimise single-path SVG" with "Prefer viewBox to width/height"

### ISSUE THREAD

**Issue by getsetbro** [jakearchibald/svgomg#99]
When "Optimise single-path SVG" is on with "Prefer viewBox to width/height" I get "Minifying error: Cannot read property 'value' of undefined".

![svgomg](https://user-images.githubusercontent.com/442793/27552575-eb53ff94-5a75-11e7-82db-4fb2f734e2b9.gif)

Tested with latest Chrome and Firefox.

**Comment by flibX0r** [comment]
Yep, the transformsWithOnePath module is SVGO is broken and incredibly out of date. Just don't use the "Optimise single-path SVG" option, it does nothing good these days.

See also #83

**Comment by alexjlockwood** [comment]
This plug-in has been removed in the latest release.
